name: CraveCart CI

on:
  push:
    branches:
      - main

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Build Backend
      run: |
        cd backend
        npm install

    - name: Build Frontend
      run: |
        cd frontend
        npm install

    - name: Docker Compose Build
      run: docker compose build